service: tagAllBotWebhook
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1

functions:
  tagAllBot:
    handler: index.handler
    events:
      - httpApi: 'POST /tagAllBot'

plugins:
  - serverless-offline
