service: tag-bot-telegram-web
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-2

functions:
  tagAllBot:
    handler: index.handler
    events:
      - httpApi: 'POST /tagAllBot'
