service: tag-bot-telegram-web
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-2
  # timeout: 60

functions:
  tagAllBot:
    handler: index.handler
    architecture: arm64
    events:
      - httpApi: 'POST /tagAllBot'

plugins:
  - serverless-offline
